/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectox;

import java.awt.Color;
import static java.awt.Color.gray;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class BasePagina extends javax.swing.JFrame {
    private int idusuario;

    // Constructor de la clase BasePagina
    public BasePagina() {
        
        Imagenes Img = new Imagenes();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setBackground(Color.black);
        
        initComponents();
        Img.SetImageLabel(logo_inicio, "src/main/java/Imagenes_Login/inicio.png",58,20);
        Img.SetImageLabel(logo_explorar, "src/main/java/Imagenes_Login/explorar.png",74,17);
        Img.SetImageLabel(logo_notif, "src/main/java/Imagenes_Login/notif.png",103,17);
        Img.SetImageLabel(logo_mens, "src/main/java/Imagenes_Login/menasjes.png",79,16);
        Img.SetImageLabel(logo_listas, "src/main/java/Imagenes_Login/listas.png",61,17);
        Img.SetImageLabel(logo_premiun, "src/main/java/Imagenes_Login/premium.png",78,17);
        Img.SetImageLabel(logo_perfil, "src/main/java/Imagenes_Login/perfil.png",59,15);
        Img.SetImageLabel(logo_mas, "src/main/java/Imagenes_Login/opciones.png",97,19);
    }

    // Método para establecer el ID de usuario
    public void setUserID(int id) {
        this.idusuario = id;
        System.out.println("ID de usuario en BasePagina: " + idusuario);

        // Después de establecer idusuario, puedes hacer las operaciones que dependen de él aquí
        String nombreUsuario = obtenerNombreUsuarioPorID(idusuario);
        System.out.println("Nombre De Usuario: " + nombreUsuario);
        Usuario.setText(nombreUsuario);
        BotonRedondo.hacerRedondeado(Usuario, 30,Color.white,gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        BotonSiguiendo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextPublicacion = new javax.swing.JTextPane();
        TextPost = new javax.swing.JTextField();
        BotonParaTi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BotonCuentaRecom2 = new javax.swing.JButton();
        BotonCuentaRecom3 = new javax.swing.JButton();
        BotonMasCuentasRecom = new javax.swing.JButton();
        LabelQueEstaPasando = new javax.swing.JLabel();
        LabelAQuienSeguir = new javax.swing.JLabel();
        BotonTendencia1 = new javax.swing.JButton();
        BotonTendencia2 = new javax.swing.JButton();
        BotonTendencia3 = new javax.swing.JButton();
        BotonMasTendencias = new javax.swing.JButton();
        BotonCuentaRecom1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextBuscar = new javax.swing.JTextPane();
        logo_premiun = new javax.swing.JLabel();
        logo_listas = new javax.swing.JLabel();
        logo_mas = new javax.swing.JLabel();
        logo_perfil = new javax.swing.JLabel();
        logo_notif = new javax.swing.JLabel();
        BotonVolverArriba = new javax.swing.JButton();
        BotonPost = new javax.swing.JButton();
        logo_inicio = new javax.swing.JLabel();
        logo_explorar = new javax.swing.JLabel();
        logo_mens = new javax.swing.JLabel();
        Usuario = new javax.swing.JButton();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonSiguiendo.setText("Siguiendo");
        BotonSiguiendo.setBorder(null);
        BotonSiguiendo.setBorderPainted(false);
        BotonSiguiendo.setContentAreaFilled(false);
        BotonSiguiendo.setFocusable(false);
        BotonSiguiendo.setOpaque(true);
        BotonSiguiendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguiendoActionPerformed(evt);
            }
        });

        TextPublicacion.setText("Escribe algo...");
        jScrollPane4.setViewportView(TextPublicacion);

        TextPost.setText("Publicacion");

        BotonParaTi.setText("<html><p style = \"font: Berlin Sans FB \">Para ti</p></html> ");
        BotonParaTi.setBorder(null);
        BotonParaTi.setBorderPainted(false);
        BotonParaTi.setContentAreaFilled(false);
        BotonParaTi.setFocusable(false);
        BotonParaTi.setOpaque(true);

        jButton1.setText("ajustes");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.setOpaque(true);

        BotonCuentaRecom2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonCuentaRecom2.setText("Cuenta recom 2");
        BotonCuentaRecom2.setBorder(null);
        BotonCuentaRecom2.setBorderPainted(false);
        BotonCuentaRecom2.setContentAreaFilled(false);
        BotonCuentaRecom2.setFocusable(false);
        BotonCuentaRecom2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonCuentaRecom2.setOpaque(true);

        BotonCuentaRecom3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonCuentaRecom3.setText("Cuenta recom 3");
        BotonCuentaRecom3.setBorder(null);
        BotonCuentaRecom3.setBorderPainted(false);
        BotonCuentaRecom3.setContentAreaFilled(false);
        BotonCuentaRecom3.setFocusable(false);
        BotonCuentaRecom3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonCuentaRecom3.setOpaque(true);

        BotonMasCuentasRecom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonMasCuentasRecom.setText("Mostrar mas");
        BotonMasCuentasRecom.setBorder(null);
        BotonMasCuentasRecom.setBorderPainted(false);
        BotonMasCuentasRecom.setContentAreaFilled(false);
        BotonMasCuentasRecom.setFocusable(false);
        BotonMasCuentasRecom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonMasCuentasRecom.setOpaque(true);

        LabelQueEstaPasando.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelQueEstaPasando.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelQueEstaPasando.setText("¿Qué esta pasando?");

        LabelAQuienSeguir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelAQuienSeguir.setText("A quien seguir");

        BotonTendencia1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonTendencia1.setText("Tendencia#1");
        BotonTendencia1.setBorder(null);
        BotonTendencia1.setBorderPainted(false);
        BotonTendencia1.setContentAreaFilled(false);
        BotonTendencia1.setFocusable(false);
        BotonTendencia1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonTendencia1.setOpaque(true);

        BotonTendencia2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonTendencia2.setText("Tendencia#2");
        BotonTendencia2.setBorder(null);
        BotonTendencia2.setBorderPainted(false);
        BotonTendencia2.setContentAreaFilled(false);
        BotonTendencia2.setFocusable(false);
        BotonTendencia2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonTendencia2.setOpaque(true);

        BotonTendencia3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonTendencia3.setText("Tendencia#3");
        BotonTendencia3.setBorder(null);
        BotonTendencia3.setBorderPainted(false);
        BotonTendencia3.setContentAreaFilled(false);
        BotonTendencia3.setFocusable(false);
        BotonTendencia3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonTendencia3.setOpaque(true);

        BotonMasTendencias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonMasTendencias.setText("Mostrar mas");
        BotonMasTendencias.setBorder(null);
        BotonMasTendencias.setBorderPainted(false);
        BotonMasTendencias.setContentAreaFilled(false);
        BotonMasTendencias.setFocusable(false);
        BotonMasTendencias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonMasTendencias.setOpaque(true);

        BotonCuentaRecom1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonCuentaRecom1.setText("Cuenta recom 1");
        BotonCuentaRecom1.setBorder(null);
        BotonCuentaRecom1.setBorderPainted(false);
        BotonCuentaRecom1.setContentAreaFilled(false);
        BotonCuentaRecom1.setFocusable(false);
        BotonCuentaRecom1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonCuentaRecom1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonTendencia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonTendencia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonTendencia3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonMasTendencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAQuienSeguir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelQueEstaPasando, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(BotonCuentaRecom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonCuentaRecom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonCuentaRecom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonMasCuentasRecom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelQueEstaPasando, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonTendencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonTendencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonTendencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonMasTendencias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelAQuienSeguir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonCuentaRecom1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonCuentaRecom2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonCuentaRecom3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonMasCuentasRecom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        TextBuscar.setBackground(new java.awt.Color(242, 242, 242));
        TextBuscar.setBorder(null);
        TextBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextBuscar.setForeground(new java.awt.Color(102, 102, 102));
        TextBuscar.setText("Buscar");
        TextBuscar.setFocusable(false);
        jScrollPane3.setViewportView(TextBuscar);

        logo_premiun.setText("+");

        logo_listas.setText("+");

        logo_mas.setText("+");

        logo_perfil.setText("+");

        logo_notif.setText("+");

        BotonVolverArriba.setText("logo");
        BotonVolverArriba.setBorder(null);
        BotonVolverArriba.setBorderPainted(false);
        BotonVolverArriba.setContentAreaFilled(false);
        BotonVolverArriba.setFocusable(false);
        BotonVolverArriba.setOpaque(true);
        BotonVolverArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverArribaActionPerformed(evt);
            }
        });

        BotonPost.setBackground(new java.awt.Color(0, 153, 255));
        BotonPost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonPost.setForeground(new java.awt.Color(255, 255, 255));
        BotonPost.setText("Postear");
        BotonPost.setBorder(null);
        BotonPost.setBorderPainted(false);
        BotonPost.setContentAreaFilled(false);
        BotonPost.setFocusable(false);
        BotonPost.setOpaque(true);
        BotonPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPostActionPerformed(evt);
            }
        });

        logo_inicio.setText("+");

        logo_explorar.setText("+");

        logo_mens.setText("+");

        Usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Usuario.setText("jButton2");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotonVolverArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonPost, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logo_mas, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(logo_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo_premiun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo_listas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo_mens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo_notif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo_explorar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonParaTi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonSiguiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextPost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(BotonSiguiendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonParaTi))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextPost, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonVolverArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logo_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(logo_explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logo_notif, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(logo_mens, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logo_listas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(logo_premiun, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(logo_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(logo_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonPost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //IMPORTANTE NO BORRAR ESTA PARTE ---------------------------- AQUI SE ESTA GUARDANDO EL ID DEL USUARIO DESDE LOGIN
    
    //IMPORTANTE NO BORRAR ESTA PARTE ---------------------------- AQUI SE ESTA GUARDANDO EL ID DEL USUARIO DESDE LOGIN
    
    
    private void BotonSiguiendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguiendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSiguiendoActionPerformed

    private void BotonVolverArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverArribaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVolverArribaActionPerformed

    private void BotonPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPostActionPerformed
        new SeccionCrearPublicacion().setVisible(true);
    }//GEN-LAST:event_BotonPostActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed
    //FUNCIONES EXTRA AGREGADAS
    //FUNCIONES EXTRA AGREGADAS
    //FUNCIONES EXTRA AGREGADAS
    public String obtenerNombreUsuarioPorID(int usu) {
    String nombreUsuario = null;
    try (Connection conn = DriverManager.getConnection("jdbc:ucanaccess://X.accdb")) {
        String sql = "SELECT user_handle FROM usuarios WHERE user_id = ?";
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, usu);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                nombreUsuario = rs.getString("user_handle");
            }
        }
    } catch (SQLException ex) {
        System.out.println("Error con la base de datos ");
        ex.printStackTrace();
    }
    System.out.println("Nombre De Usuario en la funcion: " + nombreUsuario);
    return nombreUsuario;
}

    
    
    //FUNCIONES EXTRA AGREGADAS
    //FUNCIONES EXTRA AGREGADAS
    //FUNCIONES EXTRA AGREGADAS
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasePagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasePagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasePagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasePagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasePagina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCuentaRecom1;
    private javax.swing.JButton BotonCuentaRecom2;
    private javax.swing.JButton BotonCuentaRecom3;
    private javax.swing.JButton BotonMasCuentasRecom;
    private javax.swing.JButton BotonMasTendencias;
    private javax.swing.JButton BotonParaTi;
    private javax.swing.JButton BotonPost;
    private javax.swing.JButton BotonSiguiendo;
    private javax.swing.JButton BotonTendencia1;
    private javax.swing.JButton BotonTendencia2;
    private javax.swing.JButton BotonTendencia3;
    private javax.swing.JButton BotonVolverArriba;
    private javax.swing.JLabel LabelAQuienSeguir;
    private javax.swing.JLabel LabelQueEstaPasando;
    private javax.swing.JTextPane TextBuscar;
    private javax.swing.JTextField TextPost;
    private javax.swing.JTextPane TextPublicacion;
    private javax.swing.JButton Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logo_explorar;
    private javax.swing.JLabel logo_inicio;
    private javax.swing.JLabel logo_listas;
    private javax.swing.JLabel logo_mas;
    private javax.swing.JLabel logo_mens;
    private javax.swing.JLabel logo_notif;
    private javax.swing.JLabel logo_perfil;
    private javax.swing.JLabel logo_premiun;
    // End of variables declaration//GEN-END:variables
}
