/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectox;

/**
 *
 * @author user
 */
public class SeccionNotificaciones extends javax.swing.JFrame {

    /**
     * Creates new form SeccionNotificaciones
     */
    public SeccionNotificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSecccionNotificaciones = new javax.swing.JLabel();
        BotonTodoNotificaciones = new javax.swing.JButton();
        BotonVerificadoNotificaciones = new javax.swing.JButton();
        BotonMencionesNotificaciones = new javax.swing.JButton();
        BotonNotificacionEjemplo1 = new javax.swing.JButton();
        TextoNotificacion1 = new javax.swing.JTextField();
        BotonNotificacionEjemplo2 = new javax.swing.JButton();
        TextoNotificacion2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelSecccionNotificaciones.setText("Notificaciones");

        BotonTodoNotificaciones.setText("Todo");
        BotonTodoNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTodoNotificacionesActionPerformed(evt);
            }
        });

        BotonVerificadoNotificaciones.setText("Verificado");

        BotonMencionesNotificaciones.setText("Menciones");

        BotonNotificacionEjemplo1.setText("Notificacion Ej#1");

        TextoNotificacion1.setText("Texto notificacion");

        BotonNotificacionEjemplo2.setText("Notificacion Ej#2");

        TextoNotificacion2.setText("Texto notificacion");
        TextoNotificacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNotificacion2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoNotificacion2)
                    .addComponent(TextoNotificacion1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelSecccionNotificaciones)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonTodoNotificaciones)
                        .addGap(63, 63, 63)
                        .addComponent(BotonVerificadoNotificaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(BotonMencionesNotificaciones)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonNotificacionEjemplo1)
                            .addComponent(BotonNotificacionEjemplo2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelSecccionNotificaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonTodoNotificaciones)
                    .addComponent(BotonVerificadoNotificaciones)
                    .addComponent(BotonMencionesNotificaciones))
                .addGap(18, 18, 18)
                .addComponent(BotonNotificacionEjemplo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoNotificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonNotificacionEjemplo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoNotificacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTodoNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTodoNotificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonTodoNotificacionesActionPerformed

    private void TextoNotificacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNotificacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNotificacion2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeccionNotificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeccionNotificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeccionNotificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeccionNotificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeccionNotificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMencionesNotificaciones;
    private javax.swing.JButton BotonNotificacionEjemplo1;
    private javax.swing.JButton BotonNotificacionEjemplo2;
    private javax.swing.JButton BotonTodoNotificaciones;
    private javax.swing.JButton BotonVerificadoNotificaciones;
    private javax.swing.JLabel LabelSecccionNotificaciones;
    private javax.swing.JTextField TextoNotificacion1;
    private javax.swing.JTextField TextoNotificacion2;
    // End of variables declaration//GEN-END:variables
}
